### ISSUE TITLE
There is no easy way to set number of people in the group instead of %

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#745]
There is no easy way to set number of people in the group instead of %

**Comment by dmytro-almighty** [comment]
The feature can be implemented with sender wallet, planning it for 3.0.7 or 3.0.8. We are limiting modifications of DAO policy in the Astro UI, because there is not way to modify it in granular way, and we need to bypass entire object through the HTTP GET method to wallet - and its breaching URL size limitations (2mb)
