### ISSUE TITLE
Buckey by Feeds / Communities rather than Mine / Global

### ISSUE THREAD

**Issue by RomaSha2010** [near-daos/astro-ui#98]
Issue 4 https://github.com/near-daos/astro-ui/issues/91

Order:

My Feed
Global Feed

--

My DAOs
All Communities

-- 

![image](https://user-images.githubusercontent.com/94607182/144018501-fb82dcdc-664b-46e1-a1ef-b87fdf59cdb7.png)

Example:
![image](https://user-images.githubusercontent.com/94607182/144018749-4d62d6d6-391e-4e79-a80d-3261cc42f27f.png)

**Comment by dmytro-almighty** [comment]
We are planning to get rid of the sidebar in the nearest feature. The global feed makes minimal sense since the user cannot interact with 99% of the global proposals. Also, grouping should be done by permissions level - currently, UI clearly separates what is available for logged in and what is available for non-authorized users.
